eleanor-api:
  restart: always
  build: ./eleanor
  ports:
    - "80:5000"
  volumes:
    - ./eleanor:/opt/eleanor
  links:
    - mysql
    - redis
    - mysql-read
  command: /usr/local/bin/gunicorn -w 1 -b 0.0.0.0:5000 -k gevent eleanor.eleanor:app --reload

eleanor-tasks:
  restart: always
  build: ./eleanor
  environment:
    - C_FORCE_ROOT=1
  volumes:
    - ./eleanor:/opt/eleanor
  links:
    - mysql
    - redis
    - mysql-read
  command: /usr/local/bin/celery -A start_celery worker -l debug -P gevent

mysql:
  restart: always
  image: mysql:5.6
  environment:
    - MYSQL_ROOT_PASSWORD=foobar
    - MYSQL_DATABASE=eleanordb
    - MYSQL_USER=eleanordbuser
    - MYSQL_PASSWORD=foobar123
  ports:
    - "3306:3306"
  volumes:
    - ./mysql-data:/var/lib/mysql

mysql-read:
  restart: always
  image: mysql:5.6
  environment:
    - MYSQL_ROOT_PASSWORD=foobar
    - MYSQL_DATABASE=eleanordb
    - MYSQL_USER=eleanordbuser
    - MYSQL_PASSWORD=foobar123
  ports:
    - "3300:3306"
  volumes:
    - ./mysql-dataread:/var/lib/mysql


redis:
  image: redis:latest


